"""create polymophic attachments tables

Revision ID: 85269b36e63a
Revises: 8b73e1a7ba46
Create Date: 2021-07-04 17:20:51.492684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85269b36e63a'
down_revision = '8b73e1a7ba46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_ext', sa.String(length=10), nullable=True),
    sa.Column('file_link', sa.String(), nullable=True),
    sa.Column('attached_to', sa.String(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('resolution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolutions.question_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    # ### end Alembic commands ###
