"""polymorphic-joined-table

Revision ID: 3b0caa452086
Revises: 8b73e1a7ba46
Create Date: 2021-07-04 17:52:37.965928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0caa452086'
down_revision = '8b73e1a7ba46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_ext', sa.String(length=10), nullable=True),
    sa.Column('file_link', sa.String(), nullable=True),
    sa.Column('attached_to', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resolution_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolutions.question_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resolution_attachment')
    op.drop_table('note_attachment')
    op.drop_table('question_attachment')
    op.drop_table('attachments')
    # ### end Alembic commands ###
