"""empty message

Revision ID: 0124b0ea26b0
Revises: 
Create Date: 2021-07-20 15:09:56.631581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0124b0ea26b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_ext', sa.String(length=10), nullable=True),
    sa.Column('file_link', sa.String(), nullable=True),
    sa.Column('attached_to', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('discriminant', sa.Enum('stood', 'ta', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('bug', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stoods',
    sa.Column('stoods_id', sa.Integer(), nullable=False),
    sa.Column('heroku_url', sa.String(), nullable=True),
    sa.Column('scorecard_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['stoods_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('stoods_id')
    )
    op.create_table('tas',
    sa.Column('ta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ta_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('ta_id')
    )
    op.create_table('metadata_questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('time_question_opened', sa.String(length=10), nullable=True),
    sa.Column('time_question_answered', sa.String(length=10), nullable=True),
    sa.Column('time_question_closed', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resolutions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('note_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resolution_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolutions.question_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resolution_attachment')
    op.drop_table('note_attachment')
    op.drop_table('resolutions')
    op.drop_table('question_attachment')
    op.drop_table('notes')
    op.drop_table('metadata_questions')
    op.drop_table('tas')
    op.drop_table('stoods')
    op.drop_table('questions')
    op.drop_table('users')
    op.drop_table('attachments')
    # ### end Alembic commands ###
