"""create questions, notes, resolutions tables

Revision ID: 8b73e1a7ba46
Revises: ffdc0a98111c
Create Date: 2021-07-04 17:10:51.931893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b73e1a7ba46'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'questions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=True),
        sa.Column('goal', sa.Text(), nullable=True),
        sa.Column('bug', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'metadata_questions',
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('time_question_opened', sa.String(length=10), nullable=True),
        sa.Column('time_question_answered', sa.String(length=10), nullable=True),
        sa.Column('time_question_closed', sa.String(length=10), nullable=True),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
        sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table(
        'notes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'resolutions',
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('body', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
        sa.PrimaryKeyConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resolutions')
    op.drop_table('notes')
    op.drop_table('metadata_questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
