"""adding some attachments

Revision ID: 50f8512dafb6
Revises: 825d017ee5b2
Create Date: 2021-08-06 09:11:35.196013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50f8512dafb6'
down_revision = '825d017ee5b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'attachments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('file_ext', sa.String(length=10), nullable=True),
        sa.Column('file_link', sa.String(), nullable=True),
        sa.Column('attached_to', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_table(
        'question_attachment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['attachments.id'], ),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_table(
        'note_attachment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('note_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['attachments.id'], ),
        sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_table(
        'resolution_attachment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('resolution_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['attachments.id'], ),
        sa.ForeignKeyConstraint(['resolution_id'], ['resolutions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('questions', 'resolved_status',
               existing_type=postgresql.ENUM('open', 'archived', 'closed', 'retired', name='status'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'resolved_status',
               existing_type=postgresql.ENUM('open', 'archived', 'closed', 'retired', name='status'),
               nullable=False)
    op.drop_table('resolution_attachment')
    op.drop_table('note_attachment')
    op.drop_table('question_attachment')
    op.drop_table('attachments')
    # ### end Alembic commands ###
