"""add tas and stoods tables

Revision ID: 67ba99ab86c5
Revises: 8be6cc251778
Create Date: 2021-08-05 07:33:56.627390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ba99ab86c5'
down_revision = '8be6cc251778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'stoods',
        sa.Column('stoods_id', sa.Integer(), nullable=False),
        sa.Column('heroku_url', sa.String(), nullable=True),
        sa.Column('scorecard_url', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['stoods_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('stoods_id')
    )
    op.create_table(
        'tas',
        sa.Column('ta_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['ta_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('ta_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tas')
    op.drop_table('stoods')
    # ### end Alembic commands ###
