"""add users and questions table

Revision ID: 8be6cc251778
Revises:
Create Date: 2021-08-05 07:27:18.012018

"""
from alembic import op
import sqlalchemy as sa
#...
from sqlalchemy.orm import sessionmaker

Session = sessionmaker()

# revision identifiers, used by Alembic.
revision = '8be6cc251778'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # bind = op.get_bind()
    # session = Session(bind=bind)
    # session.execute('DROP TYPE roles')
    # session.drop_all()

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=40), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('discriminant', sa.Enum('stood', 'ta', name='role'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    op.create_table(
        'questions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=True),
        sa.Column('goal', sa.Text(), nullable=True),
        sa.Column('bug', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('resolved_status', sa.Enum('open', 'archived', 'closed', 'retired',name='status'), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute('DROP TYPE roles')
    op.drop_table('questions')
    op.drop_table('users')
    # ### end Alembic commands ###
