"""add metadata_questions table

Revision ID: a0c1ae4e5bea
Revises: 67ba99ab86c5
Create Date: 2021-08-05 07:37:28.799909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c1ae4e5bea'
down_revision = '67ba99ab86c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'metadata_questions',
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('time_question_opened', sa.Time(timezone=10), nullable=True),
        sa.Column('time_question_answered', sa.Time(timezone=10), nullable=True),
        sa.Column('time_question_closed', sa.Time(timezone=10), nullable=True),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
        sa.PrimaryKeyConstraint('question_id')\
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata_questions')
    # ### end Alembic commands ###
